models/watchlist.py
from pony.orm import *
from .user import db, User
from .movie_item import MovieItem

class Watchlist(db.Entity):
    id = PrimaryKey(int, auto=True)
    is_default = Optional(bool)
    title = Optional(str)
    movie_items = Set(MovieItem, cascade_delete=True)
    user = Required(User)

routes/auth.py
import config
from datetime import datetime, timedelta
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from functools import wraps
from .generic_responses import GenericResponse
from itsdangerous import TimedJSONWebSignatureSerializer, URLSafeTimedSerializer, SignatureExpired
from loguru import logger
from models.user import User
from pony.orm import db_session, commit
from premailer import transform
from sanic import Blueprint
from sanic.response import redirect, text, html, empty
import smtplib
from smtplib import SMTPRecipientsRefused

auth = Blueprint("auth", url_prefix="/auth")

serializer = TimedJSONWebSignatureSerializer(config.JWT_SECRET)
url_safe_serializer = URLSafeTimedSerializer(config.JWT_SECRET)

def login_required(f):
	@wraps(f)
	def decorated_function(request, *args, **kwargs):
		try:
			serialized_token = request.cookies.get("token")
			if not serialized_token: raise Exception("No token, sign in")
			user_id = serializer.loads(str.encode(serialized_token)).get("user_id")
			with db_session():
				user = User.get(id=user_id)
				user.load()
			if not user: raise Exception("Could not find user.")
		except Exception as e:
			logger.info(e)
			return redirect(request.app.url_for('login_page'))
		return f(request, user, *args, **kwargs)
	return decorated_function

def is_user_logged_in(f):
	@wraps(f)
	def decorated_function(request, *args, **kwargs):
		try:
			serialized_token = request.cookies.get("token")
			if not serialized_token: raise Exception("No token, sign in")
			user_id = serializer.loads(str.encode(serialized_token)).get("user_id")
			with db_session():
				user = User.get(id=user_id)
		except Exception as e:
			logger.info(e)
			return f(request, False, *args, **kwargs)
		return f(request, True, *args, **kwargs)
	return decorated_function


def failure_message(f):
	@wraps(f)
	def decorated_function(request, *args, **kwargs):
		failure = request.args.get("failure")
		message = None
		if failure:
			# Register
			if failure == "name_missing":
				message = "First or last name missing."
			elif failure == "credential_missing":
				message = "Email or password missing."
			elif failure == "password_matching":
				message = "Passwords do not match."
			elif failure == "invalid_email":
				message = "The email address you entered is invalid."
			elif failure == "exists":
				message = "A user with that email already exists."
			elif failure == "unauthorized":
				message = "Unauthorized."
			# Login
			elif failure == "password":
				message = "Incorrect email/password combination."
			# Forgot 
			elif failure == "invalid_email":
				message = "Could not send email."
			else:
				message = "Something went wrong"
		return f(request, *args, message, **kwargs)
	return decorated_function

@auth.route("/forgot", methods=["POST"])
async def forgot_password(request):
	email = request.form.get("email")
	if not email: 
		logger.info("Bad request, no email field")
		return empty(status=400)
	
	response_html = GenericResponse.forgot_password_email_success(request.app)
	
	with db_session():
		user = User.get(email=email)
	if not user:
		logger.info("Could not find user. Returning response")
		return html(response_html)

	reset_token = url_safe_serializer.dumps(str(user.id))
	relative_url = request.app.url_for("auth.reset_password", token=reset_token)
	full_url = "{host}{location}".format(host=config.SERVER_ENDPOINT, location=relative_url)

	with db_session():
		User[user.id].active_token = reset_token

	if request.app.debug:
		response_html = GenericResponse.forgot_password_email_success(request.app, debug_link=full_url)

	response = html(response_html)

	subject = "MovieCheck - Reset your password"
	template = request.app.env.get_template("emails/forgot_password.html")
	rendered = template.render(cta_url=full_url)
	email_html = transform(rendered)
	text = "Reset your password: {}".format(full_url)

	success = request.app.debug or send_email(user.email, subject, email_html, text)
	if not success:
		logger.critical("Could not send email")
		return redirect(request.app.url_for("auth.forgot_password_page")+"?failure=invalid_email")
	else:
		return response
	
@auth.route("/reset_password/<token>", methods=["GET"])
async def reset_password_page(request, token):
	global url_safe_serializer
	try:
		user_id = url_safe_serializer.loads(token, max_age=60*60*24)
		with db_session():
			user = User.get(id=user_id, active_token=token)
		if not user: raise Exception()
	except SignatureExpired as e:
		return html(GenericResponse.token_expired(request.app))
	except Exception as e:
		return html(GenericResponse.token_invalid(request.app))

	template = request.app.env.get_template("change-password.html")
	return html(template.render(token=token))

@auth.route("/reset_password/<token>", methods=["POST"])
async def reset_password(request, token):
	global url_safe_serializer
	try:
		user_id = url_safe_serializer.loads(token, max_age=60*60*24)
		with db_session():
			user = User.get(id=user_id, active_token=token)
		if not user: raise Exception()
	except SignatureExpired as e:
		return html(GenericResponse.token_expired(request.app))
	except Exception as e:
		return html(GenericResponse.token_invalid(request.app))

	try:
		password = request.form.get("password")
		confirm_password = request.form.get("confirm_password")
		if not confirm_password or not password: raise Exception("credential_missing")
		if password != confirm_password: raise Exception("password_matching")
	except Exception as e:
		logger.info(e)
		return redirect(request.app.url_for("reset_password_page")+"?failure={}".format(e))

	password_hash = User.hash_password(password)
	with db_session():
		User[user_id].set(password_hash=password_hash, active_token="")

	response_html = GenericResponse.password_reset_success(request.app)
	return html(response_html)

@auth.route("/register", methods=["POST"])
async def register(request):
	try:
		first_name = request.form.get("first_name").strip()
		last_name = request.form.get("last_name").strip()
		email = request.form.get("email").strip()
		password = request.form.get("password")
		confirm_password = request.form.get("confirm_password")
		if not first_name or not last_name: raise Exception("name_missing")
		if not email or not password: raise Exception("credential_missing")
		if password != confirm_password: raise Exception("password_matching")
	except Exception as e:
		logger.info(e)
		return redirect(request.app.url_for("register_page")+"?failure={}".format(e))
	
	with db_session():
		if User.exists(email=email):
			logger.info("User with email {} exists.".format(email))
			return redirect(request.app.url_for("register_page")+"?failure=exists")
	
		password_hash = User.hash_password(password)
		user = User(
			email=email, 
			password_hash=password_hash, 
			first_name=first_name, 
			last_name=last_name,
			date_registered=datetime.now()
		)

	with db_session():
		user = User.get(email=email)
		temp_token = url_safe_serializer.dumps(str(user.id))
	return redirect(request.app.url_for("auth.send_verification_email", token=temp_token))

@auth.route("/send_verification/<token>")
def send_verification_email(request, token):
	global url_safe_serializer
	try:
		user_id = url_safe_serializer.loads(token, max_age=10)
	except Exception as e:
		response_html = GenericResponse.token_invalid(request.app)
		return html(response_html)
	
	verification_token = url_safe_serializer.dumps(user_id)
	with db_session():
		user = User.get(id=user_id)
	if not user:
		return html("<p>Something went wrong...</p><a href='/'>")

	verification_url = "{host}{location}".format(
		host=config.SERVER_ENDPOINT, 
		location=request.app.url_for("auth.verify_email", token=verification_token)
	)

	subject = "MovieCheck - Verify your email"
	template = request.app.env.get_template("emails/confirm_email.html")
	rendered = template.render(cta_url=verification_url)
	email_html = transform(rendered)
	text = "Verify your email: {}".format(verification_url)

	success = request.app.debug or send_email(user.email, subject, email_html, text)
	if not success:
		user.delete()
		return redirect(request.app.url_for("register_page")+"?failure=invalid_email")

	return html(GenericResponse.verification_email_success(request.app, debug_link=verification_url))
	

@auth.route("/verify/<token>")
async def verify_email(request, token):
	global url_safe_serializer
	token_issue = None
	try:
		user_id = url_safe_serializer.loads(token, max_age=60*60*24)
	except SignatureExpired as e:
		user_id = url_safe_serializer.loads(token)
		with db_session():
			User.get(id=user_id).delete()
		return html(GenericResponse.token_expired(request.app))
	except Exception as e:
		return html(GenericResponse.token_invalid(request.app))
	
	with db_session():
		User[user_id].set(is_verified=True)

	return html(GenericResponse.email_verify_success(request.app))
	

@auth.route("/login", methods=["POST"])
async def login(request):
	email = request.form.get("email")
	password = request.form.get("password")
	if not email or not password:
		logger.info("Missing fields")
		return redirect(request.app.url_for("login_page")+"?failure=invalid")

	with db_session():
		user = User.get(email=email)

	if not (user and user.check_password(password)):
		logger.info("User not found/incorrect password ({})".format(email))
		return redirect(request.app.url_for("login_page")+"?failure=password")
	
	if not user.is_verified:
		temp_token = url_safe_serializer.dumps(str(user.id))
		return redirect(request.app.url_for("auth.send_verification_email", token=temp_token))

	response = redirect(request.app.url_for("landing_page"))

routes/explore.py
from .auth import login_required
import config
from datetime import datetime, timedelta
from functools import wraps
from loguru import logger
from models.movie import Movie, ResultMovie
import requests
from requests_cache import CachedSession
from sanic import Blueprint
from sanic import response
from scraper import rt_trending, imdb_trending, imdb_search
from .watchlist import default_watchlist, is_in_default_watchlist

explore = Blueprint("explore", url_prefix="/explore")

async def get_trending(count=5):
	titles = imdb_trending()
	movies = []
	for title, year, imdb_id in titles[:count]:
		movie = ResultMovie()
		movie.title = title
		movie.year = year
		movie.imdb_id = imdb_id
		movies.append(movie)
	
	await ResultMovie.batch_populate_details(movies)

	return movies

@explore.route("/")
@login_required
async def root(request, user):
	# TODO: Centralize this initialization (in_watchlist, populate_details)
	template = request.app.env.get_template("explore.html")
	trending = await get_trending(5)
	await ResultMovie.batch_populate_details(trending)
	for movie in trending:
		movie.in_watchlist = is_in_default_watchlist(movie.imdb_id, user)
	return response.html(template.render(user=user, trending=[x for x in trending if x.imdb_id]))

@explore.route("/search")
@login_required
async def search(request, user):
	query = request.args.get("query", default="").strip()
	session = CachedSession(expires_after=60*60*24)
	r = session.get("http://www.omdbapi.com/", params={
		"apiKey": config.OMDB_API_KEY,
		"s": query
	})
	json = r.json()
	movies = []
	for movie_json in r.json().get("Search", []):
		if not movie_json.get("Type") in ["series", "movie"] or movie_json.get("Poster") == "N/A":
			continue
		movie = ResultMovie(imdb_id=movie_json.get("imdbID"))
		movie.in_watchlist = is_in_default_watchlist(movie.imdb_id, user)
		movies.append(movie)
	
	await Movie.batch_populate_details(movies)

	template = request.app.env.get_template("explore.html")
	return response.html(template.render(user=user, results=movies, query=query))

routes/generic_responses.py
from functools import wraps
from jinja2 import Environment, FileSystemLoader, select_autoescape

def requires_app(f):
    @wraps(f)
    def wrapper(app, *args, **kwargs):
        template = app.env.get_template("generic-response.html")
        return f(app, template, *args, **kwargs)
    return wrapper

class GenericResponse:

    @staticmethod
    @requires_app
    def forgot_password_email_success(app, template, debug_link=None):
        if debug_link:
            link = debug_link
            link_caption = "Reset your password"
        else:
            link = app.url_for("landing_page")
            link_caption = "Back"
        return template.render(
            title="Success",
            heading="Password reset link sent.",
            subheading="We've sent you a password reset link. Check your inbox.",
            link=link,
            link_caption=link_caption
        )

    @staticmethod
    @requires_app
    def token_expired(app, template):
        return template.render(
			title="Error",
			heading="Token expired",
			subheading="Please try again.",
			link=app.url_for("landing_page"),
			link_caption="Back"
		)

    @staticmethod
    @requires_app
    def token_invalid(app, template):
        return template.render(
			title="Error",
			heading="Invalid token",
			subheading="Please try again.",
			link=app.url_for("landing_page"),
			link_caption="Back"
		)

    @staticmethod
    @requires_app
    def password_reset_success(app, template):
        return template.render(
            title="Success",
            heading="Password successfully reset.",
            subheading="You may now use your new password to sign in.",
            link=app.url_for("login_page"),
            link_caption="Sign in"
        )

    @staticmethod
    @requires_app
    def verification_email_success(app, template, debug_link=None):
        if app.debug:
            link = debug_link
            link_caption = "Verify"
        else:
            link = app.url_for("landing_page")
            link_caption = "Back"

        return template.render(
            title="Success",
            heading="Email verification required.",
            subheading="We've sent you a verification email. Check your inbox.",
            link=link,
            link_caption=link_caption
        )

    @staticmethod
    @requires_app
    def email_verify_success(app, template):
        return template.render(
            title="Success",
            heading="Email verified.",
            subheading="Your email has been verified, you may now sign in.",
            link=app.url_for("login_page"),
            link_caption="Sign in"
        )

    @staticmethod
    @requires_app
    def account_deleted_success(app, template):
        return template.render(
            title="Success",
            heading="Account Deleted.",
            subheading="Your account has been deleted successfully.",
            link=app.url_for("landing_page"),
            link_caption="Back"
        ) 
    

routes/import_external.py
from .auth import login_required
import csv
from datetime import datetime, timedelta
from loguru import logger
from models.movie import ImportResultMovie
from sanic import Blueprint
from sanic import response
from .watchlist import history_id

import_external = Blueprint("import_external", url_prefix="/import")

def process_csv(file_body):
	titles = {}
	reader = csv.reader(file_body, dialect="excel")
	headers = next(reader)
	for row in reader:
		full_title, date = row
		year, month, day = [int(x) for x in date.split("/")]
		date = datetime(year=year, month=month, day=day)
		main_title = full_title.split(":")[0]
		if not main_title in titles:
			titles[main_title] = date
		elif titles[main_title] < date:
			titles[main_title] = date
		
	movies = []
	for title, date in titles.items():
		movie = ImportResultMovie(title=title, date=date)
		movies.append(movie)

	return movies

@import_external.route("/", methods=["POST"])
@login_required
async def process_upload(request, user):
	# TODO: Handle error when cannot parse file
	template = request.app.env.get_template("import.html")
	file_body = request.files['netflix-data'][0].body.decode().strip().split("\n")
	imported_items = process_csv(file_body)
	
	await ImportResultMovie.batch_populate_details(imported_items)
	
	not_imported = []
	for movie in imported_items:
		if not history_id(movie.imdb_id, movie.date, user):
			not_imported.append(movie)

	return response.html(template.render(user=user, results=[x for x in not_imported if x.imdb_id]))

@import_external.route("/")
@login_required
async def root(request, user):
	template = request.app.env.get_template("import.html")
	return response.html(template.render(user=user))

templates/account.html
{% extends "base.html" %}
{% set active_page = "account" %}

{% block head %}
{{super()}}
<link rel="stylesheet" href="/static/css/account.css">
{% endblock %}

{% block title %}Watchlist{% endblock %}

{% block content %}

<div class="container">
    <section>
        <h2><i class="icon-user"></i> Account</h2>
        <div class="col">
            <div class="row">
                <a href="{{url_for('auth.logout')}}"><button class="cta-button">Sign out</button></a>
            </div>
            <div class="row">
                <a href="#" style="color: red;" data-toggle="modal" data-target="#confirm-delete-modal"> Delete Account</a>
            </div>
        </div>

        <div class="modal fade" id="confirm-delete-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Delete Account</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                    Are you sure you would like to delete your MovieCheck account?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                        <form action="{{url_for('auth.delete_account')}}" method="POST">
                            <button type="submit" class="btn btn-danger">Delete my account</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>

</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
	{% block head %}
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet"> 
	<link rel="stylesheet" href="/static/css/style.css">
	<link rel="stylesheet" href="/static/css/icomoon.css">
	{% include "components/favicons.html" %}
	<title>MovieCheck - {% block title %}{% endblock %}</title>
	{% endblock %}
</head>
	<body>
		<div class="content">
			{% block navigation %}
			<!-- Navigation -->
			<div class="container">
				<nav class="navbar navbar-expand-lg nav-fill w-100 px-0">
					<a class="navbar-brand" href="/">
						<img style="height: 40px; width: auto;" src="/static/img/logo-full.svg" alt="MovieCheck">
					</a>
					<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon brand-main"></span>
					</button>
					<div class="collapse navbar-collapse" id="navbarText">
						<ul class="navbar-nav ml-auto">
							{% if user is not defined %}
								{% set navigation_bar = [
									("/#features", "features", "Features", ""),
									(url_for('login_page'), "sign-in", "Sign in", "")
								] -%}
							{% else %}
								{% set navigation_bar = [
									(url_for('watchlist.root'), "watchlist", "Watchlist", "icon-tv"),
									(url_for('explore.root'), "explore", "Explore", "icon-discover"),
									(url_for('account_page'), "account", user.first_name|title, "icon-user")
								] -%}
							{% endif %}
							{% set active_page = active_page|default('index') -%}
							{% for href, id, caption, icon in navigation_bar %}
							<li>
								<a class="nav-link text-dark {% if id == active_page %}active{% endif %}" href="{{ href|e }}">
									<i class="{{icon}}"></i>
									{{ caption|e }}
								</a>
							</li>
							{% endfor %}
						</ul>
					</div>
				</nav>
			</div>
			{% endblock %}

		
			{% block content %}
			{% endblock %}
		</div>
		
		<footer class="page-footer font-small blue pt-4">
			<div class="footer-copyright text-center py-3">Made by 
				<a href="https://twitter.com/stephancill" target="_blank">@stephancill</a>.
				<br>
				Data from <a href="https://www.omdbapi.com/" target="_blank" rel="noopener noreferrer">OMDB</a> and
				<a href="https://www.themoviedb.org/" target="_blank" rel="noopener noreferrer">TMDB</a>.
				<br>
				<a href="{{url_for('tos_page')}}" target="_blank" rel="noopener noreferrer">Terms of Service</a>
				<br>
				<a href="{{url_for('privacy_policy_page')}}" target="_blank" rel="noopener noreferrer">Privacy Policy</a> 
			</div>
		</footer>

		{% if not app.debug %}
		{% include "components/analytics.html" %}
		{% endif %}

		{% block scripts %}
		<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
		<script src="/static/js/base.js"></script>
		{% endblock %}
	</body>

</html>

templates/explore.html
{% extends "base.html" %}
{% set active_page = "explore" %}

{% block head %}
{{super()}}
<link rel="stylesheet" href="/static/css/explore.css">
<link rel="stylesheet" href="/static/css/movie.css">
{% endblock %}

{% block title %}Explore{% endblock %}

{% block content %}

<div class="container">
    <section class="search-container text-center">
        <form action="{{url_for('explore.search')}}" method="GET">
            <input id="search-input" type="text" placeholder="Search..." name="query" {% if query %}value="{{query}}"{% endif %}>
        </form>
    </section>
    {% if results is defined %}
    <section class="results-container">
        <h2><i class="icon-discover"></i> Results</h2>
        <div class="row">
            {% for movie in results %}
            {% if movie.poster_url %}
                {% include "components/movie.html" %}
            {% endif %}
            {% endfor %}
        </div>
    </section>
    {% else %}
    <section class="trending-container">
        <div class="gradient-background-flipped row-full"></div>
        <h2><i class="icon-trending"></i> Trending</h2>
        {% with movies = trending|batch(5)|first %}
            {% include "components/movie-list.html" %}
        {% endwith %}
    </section>
    {% endif %}
</div>

{% endblock %}

{% block scripts %}
{{super()}}
<script src="/static/js/explore.js"></script>
{% endblock %}

templates/forgot-password.html
{% extends "base.html" %}

{% block head %}
{{super()}}
<link rel="stylesheet" href="/static/css/authentication.css">
{% endblock %}

{% block title %}Forgot Password{% endblock %}

{% block content %}

<div class="container">
    <section>
        <form class="mx-auto" action="{{url_for('auth.forgot_password')}}" method="POST">
            <h2><strong>Forgot your password?</strong></h2>
            <div class="form-field">
                <h5>Email address</h5>
                <input type="email" name="email" required>
            </div>
            <div class="col align-center form-footer">
                <div class="row pb-3"><button type="submit" class="cta-button">Send recovery link</button></div>
                <div class="row mb-auto pb-3"><a class="mx-auto" href="{{url_for('register_page')}}">Need an account?</a></div>
            </div>
        </form>
    </section>
</div>


{% endblock %}

templates/import.html
{% extends "base.html" %}
{% set active_page = "explore" %}

{% block head %}
{{super()}}
<link rel="stylesheet" href="/static/css/explore.css">
<link rel="stylesheet" href="/static/css/movie.css">
{% endblock %}

{% block title %}Import{% endblock %}

{% block content %}

<div class="container">
    <section>
        <h2>Select source</h2>
        <div class="mb-3">
            <h3>Netflix Viewing Activity(.csv)</h3>
            <span><a href="https://help.netflix.com/en/node/101917" target="_blank" rel="noopener noreferrer">Help</a></span>
        </div>
        <form enctype="multipart/form-data" action="{{url_for('import_external.root')}}" method="POST">
            <input type="file" name="netflix-data" accept=".csv" required>
            <button type="submit">Upload</button>
        </form>
    </section>
    
    {% if results %}
    <section class="results-container">
        <h2><i class="icon-discover"></i> Results</h2>
        <div class="row">
            {% for movie in results %}
            <div>
                {% include "components/import-movie.html" %}
            </div>
                
            {% endfor %}
        </div>
    </section>
    {% endif %}
</div>

{% endblock %}

{% block scripts %}
{{super()}}
<script src="/static/js/import.js"></script>
{% endblock %}

templates/sign-in.html
{% extends "base.html" %}
{% set active_page = "sign-in" %}

{% block head %}
{{super()}}
<link rel="stylesheet" href="/static/css/authentication.css">
<link rel="stylesheet" href="/static/css/sign-in.css">
{% endblock %}

{% block title %}Sign In{% endblock %}

{% block content %}

<div class="container">
    <section>
        <form class="mx-auto" action="{{url_for('auth.login')}}" method="POST">
            <h2><strong>Welcome back.</strong></h2>
            {% if failure %}
            <p class="failure-message">{{failure}}</p>
            {% endif %}
            <div class="form-field">
                <h5>Email address</h5>
                <input type="email" name="email" required>
            </div>
            <div class="form-field">
                <h5>Password</h5>
                <input type="password" name="password" required>
            </div>
            <div class="col align-center form-footer">
                <div class="row pb-3"><button type="submit" class="cta-button">Sign in</button></div>
                <div class="row mt-3 pb-3"><a class="mx-auto" href="{{url_for('forgot_password_page')}}">Forgot your password?</a></div>
                <div class="row mb-auto pb-3"><a class="mx-auto" href="{{url_for('register_page')}}">Need an account?</a></div>
            </div>
        </form>
    </section>
</div>


{% endblock %}

templates/sign-up.html
{% extends "base.html" %}

{% block head %}
{{super()}}
<link rel="stylesheet" href="/static/css/authentication.css">
<link rel="stylesheet" href="/static/css/sign-up.css">
{% endblock %}

{% block title %}Sign Up{% endblock %}

{% block content %}
<div class="container">
    <section>
        <form class="mx-auto" action="{{url_for('auth.register')}}" method="POST">
            <h2><strong>Let's get started.</strong></h2>
            {% if failure %}
            <p class="failure-message">{{failure}}</p>
            {% endif %}
            <div class="row">
                <div class="form-field col-xl">
                    <h5>First name</h5>
                    <input type="name" name="first_name" required>
                </div>
                <div class="form-field col-xl">
                    <h5>Last name</h5>
                    <input type="name" name="last_name" required>
                </div>
            </div>
            <div class="form-field">
                <h5>Email address</h5>
                <input type="email" name="email" required>
            </div>
            <div class="form-field">
                <h5>Choose a new password</h5>
                <input type="password" name="password" required>
            </div>
            <div class="form-field">
                <h5>Confirm password</h5>
                <input type="password" name="confirm_password" required>
            </div>
            <div class="row align-center form-footer">
                <div class="col-xl pb-3"><button type="submit" class="cta-button">Sign up for free</button></div>
                <div class="col-xl mt-auto mb-auto ml-auto pb-3"><a href="{{url_for('login_page')}}">Already have an account?</a></div>
            </div>
            
            <!-- TODO: ToS and PP links -->
            <p>By signing up, you confirm that you've read and accepted our 
                <a href="{{url_for('tos_page')}}" target="_blank" rel="noopener noreferrer">Terms of Service</a> and 
                <a href="url_for('privacy_policy_page'" target="_blank" rel="noopener noreferrer">Privacy Policy</a>.</p>
        </form>
    </section>
</div>


{% endblock %}

templates/watchlist.html
{% extends "base.html" %}
{% set active_page = "watchlist" %}

{% block head %}
{{super()}}
<link rel="stylesheet" href="/static/css/watchlist.css">
<link rel="stylesheet" href="/static/css/movie.css">
<link rel="stylesheet" href="/static/css/rating.css">
{% endblock %}

{% block title %}Watchlist{% endblock %}

{% block content %}

<div class="container">
    <section class="watchlist-container">
        <h2><i class="icon-tv"></i> {{user.first_name|title}}'s Watchlist</h2>
        {% if watchlist|length == 0 %}
        <h3>Go to the <a href="{{url_for('explore.root')}}">Explore</a> tab and find some movies to add here.</h3>
        {% else %}
        <div class="gradient-background row-full"></div>
        {% with movies = watchlist %}
            {% include "components/movie-list.html" %}
        {% endwith %}
        {% endif %}
    </section>
    <section>
        <h2><i class="icon-history" style="font-size: 27px;"></i> History</h2>
        {% if history|length == 0 %}
        <h3>Movies that you've watched will show up here.</h3>
        {% else %}
        <div class="history-container">
            <table class="mx-auto">
                <tr>
                    <th>DATE</th>
                    <th>TITLE</th>
                    <th>GENRES</th>
                    <th>MY RATING</th>
                    <th></th>
                </tr>
                {% for movie in history %}
                    {% include "components/history-row.html" %}
                {% endfor %}
            </table>
        </div>
        {% endif %}
        <div class="mt-3">
            <a href="{{url_for('import_external.root')}}">Import watch history</a>
        </div>
    </section>
</div>

{% endblock %}

{% block scripts %}
{{super()}}
<script src="/static/js/watchlist.js"></script>
{% endblock %}