models/movie.py
import asyncio
import config
from concurrent.futures import ThreadPoolExecutor
from functools import wraps
from loguru import logger
from requests_cache import CachedSession
import scraper

def requires_omdb_json(f):
    @wraps(f)
    def wrapper(self, *args, **kwargs):
        if not self.omdb_json:
            session = CachedSession(expires_after=60*60*24*7)
            if self.imdb_id:
                r = session.get("http://www.omdbapi.com/", params={
                    "apiKey": config.OMDB_API_KEY,
                    "i": self.imdb_id
                })
                self.omdb_json = r.json()
            else:
                r = session.get("http://www.omdbapi.com/", params={
                    "apiKey": config.OMDB_API_KEY,
                    "t": self.title,
                    "y": self.year
                })
                self.omdb_json = r.json()
        return f(self, self.omdb_json, *args, **kwargs)
    return wrapper

class Movie:
    def __init__(self, title=None, year=None, imdb_id=None, type=None, omdb_json=None):
        self.title = title
        self.year = year
        self.imdb_id = imdb_id
        self.type = type
        self.omdb_json = omdb_json

    @requires_omdb_json
    def populate_details(self, json):     
        self.year = json.get("Year")
        self.title = json.get("Title")
        self.imdb_id = json.get("imdbID")
        self.type = json.get("Type")

    @staticmethod
    async def batch_populate_details(movies):
        with ThreadPoolExecutor(max_workers=20) as executor:
            loop = asyncio.get_event_loop()
            futures = [loop.run_in_executor(executor, movie.populate_details) for movie in movies]
            await asyncio.gather(*futures, return_exceptions=True)
        
class ResultMovie(Movie):
    def __init__(self, poster_url=None, rt_rating=None, rt_url=None, imdb_rating=None, imdb_url=None, in_watchlist=False, *args, **kwargs):
        self.poster_url = poster_url
        self.imdb_rating = imdb_rating
        self.imdb_url = imdb_url
        self.rt_rating = rt_rating
        self.rt_url = rt_url
        self.in_watchlist = in_watchlist
        super().__init__(*args, **kwargs)

    @requires_omdb_json
    def populate_details(self, json):
        super().populate_details()
        self.poster_url = json.get("Poster")
        self.imdb_rating = json.get("imdbRating")
        if json.get("imdbID"):
            self.imdb_url = "https://www.imdb.com/title/" + json.get("imdbID")
        self.rt_rating = scraper.rt_rating(self.title, self.year)
        if self.rt_rating:
            self.rt_url = scraper.rt_url(self.title, self.year)
        
        
class WatchlistMovie(Movie):
    def __init__(self, poster_url=None, in_watchlist=False, *args, **kwargs):
        self.poster_url = poster_url
        self.in_watchlist = in_watchlist
        super().__init__(*args, **kwargs)

    @requires_omdb_json
    def populate_details(self, json):
        super().populate_details()
        self.poster_url = json.get("Poster")
    
class HistoryMovie(Movie):
    def __init__(self, genres=None, id=None, date=None, rating=None, *args, **kwargs):
        self.genres = genres
        self.id = id
        self.date = date
        self.rating = rating
        super().__init__(*args, **kwargs)

    @requires_omdb_json
    def populate_details(self, json):
        super().populate_details()
        self.genres = json.get("Genre", "").split(", ")

class ImportResultMovie(WatchlistMovie):
    def __init__(self, date=None, *args, **kwargs):
        self.date = date
        super().__init__(*args, **kwargs)

routes/watchlist.py
from .auth import login_required
import config
from datetime import datetime, timedelta
from functools import wraps
from loguru import logger
from models.user import User
from models.watchlist import Watchlist
from models.movie_item import MovieItem
from models.movie import Movie, WatchlistMovie, HistoryMovie
from pony.orm import db_session, select
from sanic import Blueprint
from sanic import response

watchlist = Blueprint("watchlist", url_prefix="/watchlist")

@db_session
def is_in_default_watchlist(imdb_id, user):
	return Watchlist.select(
		lambda w: imdb_id in w.movie_items.imdb_id and 
		w.is_default and 
		w.user.id == user.id).first() != None

@db_session
def is_in_history(imdb_id, user):
	return User.select(
		lambda u: imdb_id in u.watch_history.imdb_id and
		user.id == u.id
	).first() != None

@db_session
def history_id(imdb_id, date, user):
	return User.select(
		lambda u: imdb_id in u.watch_history.imdb_id and
		date in u.watch_history.date and
		user.id == u.id
	).first()
	
def default_watchlist(f):
	@wraps(f)
	def decorated_function(request, user, *args, **kwargs):
		with db_session(strict=False):
			watchlist = Watchlist.select(lambda w: w.user.id == user.id).first()
			if not watchlist:
				user = User.get(id=user.id)
				watchlist = Watchlist(user=user, is_default=True)
			watchlist.movie_items.load()
		return f(request, user, watchlist, *args, **kwargs)
	return decorated_function

@watchlist.route("/")
@login_required
@default_watchlist
async def root(request, user, watchlist):
	watchlist_movies = []
	for item in sorted(watchlist.movie_items, key=lambda x: x.date, reverse=True):
		movie = WatchlistMovie(imdb_id=item.imdb_id, in_watchlist=True)
		watchlist_movies.append(movie)

	await Movie.batch_populate_details(watchlist_movies)

	history = []
	# For some reason watch_history does not preload properly
	with db_session():
		user = User.get(id=user.id)
		for item in sorted(user.watch_history, key=lambda x: x.date, reverse=True):
			movie = HistoryMovie(imdb_id=item.imdb_id, id=item.id, date=item.date, rating=item.rating)
			history.append(movie)
	
	await Movie.batch_populate_details(history)

	template = request.app.env.get_template("watchlist.html")
	rendered = template.render(user=user, watchlist=watchlist_movies, history=history)
	return response.html(rendered)

@watchlist.route("/add/<movie_id>", methods=["POST"])
@login_required
@default_watchlist
async def add(request, user, watchlist, movie_id):
	logger.debug(movie_id)
	if not is_in_default_watchlist(movie_id, user):
		with db_session():
			watchlist = Watchlist.get(id=watchlist.id)
			item = MovieItem(imdb_id=movie_id, date=datetime.now(), watchlist=watchlist)
	return response.empty()

@watchlist.route("/seen/<movie_id>", methods=["POST"])
@login_required
@default_watchlist
async def seen(request, user, watchlist, movie_id):
	logger.debug(movie_id)
	with db_session():
		# TODO: Catche error if does not exist
		watchlist = Watchlist.get(id=watchlist.id)
		user = User.get(id=user.id)
		MovieItem.select(lambda m: m.imdb_id == movie_id and m.watchlist.id == watchlist.id).delete()
		date_string = request.args.get("date", None)
		if date_string:
			date = datetime.strptime(date_string, "%Y-%m-%d")
		else:
			date = datetime.now()
		movie = MovieItem(imdb_id=movie_id, date=date, user=user)

	return response.empty()


@watchlist.route("/remove/<movie_id>", methods=["POST"])
@login_required
@default_watchlist
async def remove(request, user, watchlist, movie_id):
	logger.debug(movie_id)
	with db_session():
		watchlist = Watchlist.get(id=watchlist.id)
		MovieItem.select(lambda m: m.imdb_id == movie_id and m.watchlist.id == watchlist.id).delete()
	return response.empty()

@watchlist.route("/remove_history/<item_id>", methods=["POST"])
@login_required
async def remove_history(request, user, item_id):
	logger.debug(item_id)
	with db_session():
		date_string = request.args.get("date", None)
		if date_string:
			date = datetime.strptime(date_string, "%Y-%m-%d")
			MovieItem.select(
				lambda m: m.id == item_id and 
				m.date == date and 
				m.user.id == user.id
			).delete()
		else:
			MovieItem.select(lambda m: m.id == item_id).delete()
	return response.empty()

@watchlist.route("/edit_history/<item_id>", methods=["POST"])
@login_required
async def edit_history(request, user, item_id):
	logger.debug(item_id)
	logger.debug(request.form.get("date"))
	date_string = request.form.get("date")
	if date_string:
		with db_session():
			movie = MovieItem.select(lambda m: m.id == item_id and m.user.id == user.id).first()
			movie.date = datetime.strptime(date_string, "%Y-%m-%d")
	return response.empty()

@watchlist.route("/rating/<item_id>", methods=["POST"])
@login_required
async def rate_item(request, user, item_id):
	try:
		rating = int(request.form.get("rating"))
		with db_session():
			movie = MovieItem.get(id=item_id)
			if not movie or movie.user.id != user.id:
				return response.empty()
			movie.rating = rating
	except Exception as e:
		logger.error(e)
		
	return response.empty()
	

templates/components/analytics.html
<noscript><img src="https://shynet.stephancill.pw/ingress/8ee3ab95-5b22-4edd-b492-ef4fa9e7ad46/pixel.gif"></noscript>
<script src="https://shynet.stephancill.pw/ingress/8ee3ab95-5b22-4edd-b492-ef4fa9e7ad46/script.js"></script> 

templates/components/favicons.html
<link rel="shortcut icon" href="/static/img/favicons/favicon.ico">
<link rel="icon" sizes="16x16 32x32 64x64" href="/static/img/favicons/favicon.ico">
<link rel="icon" type="image/png" sizes="196x196" href="/static/img/favicons/favicon-192.png">
<link rel="icon" type="image/png" sizes="160x160" href="/static/img/favicons/favicon-160.png">
<link rel="icon" type="image/png" sizes="96x96" href="/static/img/favicons/favicon-96.png">
<link rel="icon" type="image/png" sizes="64x64" href="/static/img/favicons/favicon-64.png">
<link rel="icon" type="image/png" sizes="32x32" href="/static/img/favicons/favicon-32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/static/img/favicons/favicon-16.png">
<link rel="apple-touch-icon" href="/static/img/favicons/favicon-57.png">
<link rel="apple-touch-icon" sizes="114x114" href="/static/img/favicons/favicon-114.png">
<link rel="apple-touch-icon" sizes="72x72" href="/static/img/favicons/favicon-72.png">
<link rel="apple-touch-icon" sizes="144x144" href="/static/img/favicons/favicon-144.png">
<link rel="apple-touch-icon" sizes="60x60" href="/static/img/favicons/favicon-60.png">
<link rel="apple-touch-icon" sizes="120x120" href="/static/img/favicons/favicon-120.png">
<link rel="apple-touch-icon" sizes="76x76" href="/static/img/favicons/favicon-76.png">
<link rel="apple-touch-icon" sizes="152x152" href="/static/img/favicons/favicon-152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/static/img/favicons/favicon-180.png">
<meta name="msapplication-TileColor" content="#FFFFFF">
<meta name="msapplication-TileImage" content="/static/img/favicons/favicon-144.png">
<meta name="msapplication-config" content="/static/img/favicons/browserconfig.xml">

templates/components/history-row.html
{% set date = movie.date.strftime('%Y-%m-%d') %}
<tr>
    <td class="shrink date-container" style="padding-right: 40px;">
        <div class="date">
            {{date}}
            <button type="submit"><i class="icon-pencil"></i></button>
        </div>
        <form action="{{url_for('watchlist.edit_history', item_id=movie.id)}}" method="POST" style="display: none;" class="reload-on-submit">
            <input type="date" value="{{date}}" name="date">
            <button type="submit"><i class="icon-check"></i></button>
        </form>
    </td>
    <td class="expand">
        {% if movie.type == "series" %}
        <i class="icon-tv"></i>
        {% elif movie.type == "movie" %}
        <i class="icon-film" title="Movie" alt="Movie"></i>
        {% endif %}
        <a href="https://www.imdb.com/title/{{movie.imdb_id}}" target="_blank" rel="noopener noreferrer">
            <span>{{movie.title}} ({{movie.year}})</span>
        </a></td>
    <td class="shrink">{{movie.genres|batch(3)|first|join(", ")}}</td>
    <td class="expand" style="white-space: nowrap;">
        <form class="rating-form" action="{{url_for('watchlist.rate_item', item_id=movie.id)}}" method="POST" autocomplete="off">
            {% for i in range(1, 6)[::-1] %}
            {% set id = movie.imdb_id + date + "-" + i|string  %}
            <input type="radio" name="rating" value="{{i}}" id="{{id}}" 
                {% if movie.rating and movie.rating == i %}
                checked="checked"
                {% endif %}
            >
            <label for="{{id}}"><i></i></label>
            {% endfor %}
            {% if not movie.rating %}
            <input type="radio" name="rating" value="default" checked="checked">
            {% endif %}
            
        </form>
    </td>
    <td>
        <form action="{{url_for('watchlist.remove_history', item_id=movie.id)}}" method="POST" class="reload-on-submit">
            <button type="submit" class="edit-button"><i class="icon-bin"></i></button>
        </form>
    </td>
</tr>

templates/components/import-movie.html
{% extends "components/movie.html" %}

{% set date = movie.date.strftime('%Y-%m-%d') %}

{% block buttons %}
<div class="movie-actions"> 
    <form action="{{url_for('watchlist.seen', movie_id=movie.imdb_id)}}?date={{date}}" method="POST">
        <button class="left" type="submit"><i class="icon-history"></i><span>Add</span></button>
    </form>
</div>
{% endblock %}

{% block footer %}
{{super()}}
<div>Seen: {{date}}</div>
{% endblock %}

templates/components/movie-list.html
<div class="list-row row-full">
    <div class="filler"></div>
    <button class="scroll-button left">
        <img  src="/static/img/watchlist/next-button.svg" alt="">
    </button>
    {% for movie in movies %}
        {% include "components/movie.html" %}
    {% endfor %}
    <button class="scroll-button right">
        <img  src="/static/img/watchlist/next-button.svg" alt="">
    </button>
    
    <div class="filler-end"></div>
</div>

templates/components/movie.html
<div class="movie">
    {% block buttons %}
    <div class="movie-actions {{'watchlist' if movie.in_watchlist else 'not-watchlist'}}">
        <div class="not-watchlist-buttons">
            <form action="{{url_for('watchlist.add', movie_id=movie.imdb_id)}}" method="POST">
                <button class="left" type="submit"><i class="icon-plus"></i><span>Add</span></button>
            </form>
        </div>
        <div class="watchlist-buttons">
            <form action="{{url_for('watchlist.remove', movie_id=movie.imdb_id)}}" method="POST">
                <button class="right" style="background-color: #727272;" type="submit"><i class="icon-cross"></i><span>Remove</span></button>
            </form>
            <form action="{{url_for('watchlist.seen', movie_id=movie.imdb_id)}}" method="POST">
                <button class="left" type="submit"><i class="icon-tick"></i><span>Seen</span></button>
            </form>
        </div>
    </div>
    {% endblock %}
    
    {% block footer %}
    <div class="gradient-overlay">
        {% if movie.rt_rating is string %}
        <a href="{{movie.rt_url}}" target="_blank">
            <div class="rating rt-rating">
                <img src="/static/img/rt-logo.png" alt="">
                <span>{{movie.rt_rating}}</span>
            </div>
        </a>
        {% endif %}
        {% if movie.imdb_rating is string %}
        <a href="https://www.imdb.com/title/{{movie.imdb_id}}" target="_blank">
            <span class="rating imdb-rating">
                <img src="/static/img/imdb-logo.png" alt="">
                <span>{{movie.imdb_rating}}</span>
            </span>
        </a>
        {% endif %}
        <img class="poster" src="{{movie.poster_url}}" alt="">
    </div>
    <span class="title">
        {% if movie.type == "series" %}
        <i class="icon-tv" title="Series" alt="Series"></i>
        {% elif movie.type == "movie" %}
        <i class="icon-film" title="Movie" alt="Movie"></i>
        {% endif %}
        <a href="https://www.imdb.com/title/{{movie.imdb_id}}" target="_blank"> <strong>{{movie.title}}</strong> ({{movie.year}})</a>
    </span>
    {% endblock %}
</div>